### ISSUE TITLE
segfault in lv2_file_generator

### ISSUE THREAD

**Issue by michal-cab** [pierreguillot/Camomile#216]
1. **Please provide an explicit title to the issue**. 
compiled camomille according instructions - everything went well without errors/warnings.
but when trying eg.:  ./camomile -f ./Examples/Bulgroz

i got segfault:
Camomile - Plugin Generator
./builds/Bulgroz.vst3
generating ttl Bulgroz in ./builds/Bulgroz.lv2/Bulgroz.so
./camomile: line 243: 13046 Segmentation fault      LD_LIBRARY_PATH=$PWD "$ThisPath/lv2_file_generator" "$plugin_output_dir/$plugin_name.lv2/$plugin_name.$LinuxLV2Extension" $plugin_name
mv: cannot stat '/home/tao/source/Camomile/Plugins/manifest.ttl': No such file or directory
mv: cannot stat '/home/tao/source/Camomile/Plugins/Bulgroz.ttl': No such file or directory

in builds dir i see created dirs bulgros.lv2 and bulgros.vst3 dirs with files:
-rw-r--r-- 1 tao tao     1609 Nov  9 15:12 Bulgroz.pd
-rw-r--r-- 1 tao tao   453686 Nov  9 15:12 Bulgroz.png
-rwxr-xr-x 1 tao tao 41988984 Nov  9 15:12 Bulgroz.so*
-rw-r--r-- 1 tao tao      241 Nov  9 15:12 Bulgroz.txt
-rw-r--r-- 1 tao tao     3376 Nov  9 15:12 delback~.pd
-rw-r--r-- 1 tao tao      301 Nov  9 15:12 Infos.txt
-rw-r--r-- 1 tao tao     1376 Nov  9 15:12 param.change.pd
-rw-r--r-- 1 tao tao      488 Nov  9 15:12 param.get.pd
-rw-r--r-- 1 tao tao      646 Nov  9 15:12 param.set.pd
-rw-r--r-- 1 tao tao      397 Nov  9 15:12 program.get.pd

but no manifest.ttl or Bulgroz.ttl

also if i do:
./lv2_file_generator ./builds/Bulgroz.lv2/Bulgroz.so Bulgroz

i got:
generating ttl Bulgroz in ./builds/Bulgroz.lv2/Bulgroz.so
Segmentation fault

debugging:
gdb ./lv2_file_generator
...
(gdb) r ./builds/Bulgroz.lv2/Bulgroz.so Bulgroz
Starting program: /home/tao/source/Camomile/Plugins/lv2_file_generator ./builds/Bulgroz.lv2/Bulgroz.so Bulgroz
generating ttl Bulgroz in ./builds/Bulgroz.lv2/Bulgroz.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff72fe426 in std::ostream::sentry::sentry(std::ostream&) () from /lib/x86_64-linux-gnu/libstdc++.so.6

2. **Describe your environment**
    - **OS**: Debian 10 BUSTER          
          
 
no idea what i am missing/doing wrong. ev. thnx for help - i would be very happy to use my pd patches as lv2 plugins with gui :)

**Comment by pierreguillot** [comment]
This seems related to this https://github.com/pierreguillot/Camomile/issues/208. Can you confirm?

**Comment by michal-cab** [comment]
> This seems related to this #208. Can you confirm?

yes / sorry did not notice that #208 is about the same problem. so problem exists also under debian 10 64bit arch and is solved with: make CONFIG=Release

maybe to mention this in readme would be useful.
thnx for great wrapper! tested it with ardour, loaded more instances of the same plugin with different presets and it just works! :+1:

**Comment by CarloCattano** [comment]
Hello there . Thanks for this awesome project first of all . 
This issue is still present when building according to instructions in README and docs .
At last on arm64 , if ``` make ``` is used without  CONFIG Release after the build one gets segmentation faults in lv2_file_generator
